name: shell commands

on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
     - name: echo a simple string
       run: echo "a simple command"
     - name: multiline commands
       run: | 
          node -v
          npm -v
